name: Build and deploy the Angular SPA to the Azure Blob Storage container

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Build Angular App'
      run: |
        npm install
        npm run build --if-exists

    - name: 'Deploy to Azure Blob Storage'
      uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'dist'
        index-file: 'index.html'
        error-file: 'index.html'
        remove-existing-files: 'true'
        connection-string: ${{ secrets.SPA_CONNECTION_STRING }}
